name: deepcoder
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  simple_animations: ^1.3.3
  photo_view: 0.9.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assates/images/icons1.png
    - assates/images/icons3.png
    - assates/images/students/1.JPG
    - assates/images/students/2.JPG
    - assates/images/students/3.JPG
    - assates/images/students/4.JPG
    - assates/images/students/5.jpeg
    - assates/images/students/6.JPG
    - assates/images/students/7.JPG
    - assates/images/students/8.JPG
    - assates/images/students/9.JPG
    - assates/images/students/10.JPG
    - assates/images/students/11.JPG
    - assates/images/students/12.JPG
    - assates/images/students/13.JPG
    - assates/images/students/14.jpeg
    - assates/images/students/15.jpg
    - assates/images/students/16.jpg
    - assates/images/students/17.jpg
    - assates/images/students/18.jpg
    - assates/images/students/19.jpeg
    - assates/images/students/20.jpg
    - assates/images/students/21.jpg
    - assates/images/students/22.jpg
    - assates/images/students/23.jpeg
    - assates/images/students/24.jpg
    - assates/images/students/30.jpeg
    - assates/images/students/afrhh.jpg
    - assates/images/students/aml.jpg
    - assates/images/students/abtsam.jpg
    - assates/images/students/eman.jpg
    - assates/images/students/bnhn.jpg
    - assates/images/students/hnen.jpg
    - assates/images/students/hlemh.jpg
    - assates/images/students/ranea.jpg
    - assates/images/students/rnaa.jpg
    - assates/images/students/rba.jpg
    - assates/images/students/rhalmner.jpg
    - assates/images/students/rhamabod.jpg
    - assates/images/students/sarh.jpg
    - assates/images/students/shema.jpg
    - assates/images/students/shatha.jpg
    - assates/images/students/me.jpg
    - assates/images/students/Mahfouda.jpg
    - assates/images/students/whebh.jpg
    - assates/images/logo/its.jpg
    - assates/images/logo/th.jpg
    - assates/images/slider/one.jpg
    - assates/images/slider/two.jpg
    - assates/images/slider/three.jpg
    - assates/images/slider/five.jpg
    - assates/images/slider/six.jpg
    - assates/images/home1.jpg
    - assates/images/20.png
    - assates/images/home2.png
    - assates/images/home3.jpg
    - assates/images/home4.png
    - assates/images/home5.jpg
    - assates/images/nabsh/1.jpeg
    - assates/images/nabsh/2.jpeg
    - assates/images/nabsh/3.jpeg
    - assates/images/nabsh/4.jpeg
    - assates/images/nabsh/5.jpeg
    - assates/images/nabsh/7.jpeg
    - assates/images/nabsh/8.jpeg
    - assates/images/nabsh/9.jpeg
    - assates/images/nabsh/10.jpeg
    - assates/images/nabsh/11.jpeg
    - assates/images/nabsh/12.jpeg
    - assates/images/nabsh/13.jpeg
    - assates/images/nabsh/14.jpeg
    - assates/images/nabsh/15.jpeg
    - assates/images/nabsh/16.jpeg
    - assates/images/nabsh/17.jpeg
    - assates/images/nabsh/18.jpeg
    - assates/images/nabsh/19.jpeg
    - assates/images/nabsh/20.jpeg
    - assates/images/nabsh/21.jpeg
    - assates/images/nabsh/22.jpeg
    - assates/images/nabsh/23.jpeg
    - assates/images/logo/1.png
    - assates/images/logo/logo2.png
    - assates/images/logo/s1.jpg
    - assates/images/logo/s2.jpg
    - assates/images/logo/s3.jpg
    - assates/images/logo/s4.jpg
    - assates/images/logo/s5.jpg
    - assates/images/logo/s6.jpg
    - assates/images/logo/s7.jpg
    - assates/images/logo/s8.jpg
    - assates/images/master/a1.jpeg
    - assates/images/master/a2.jpeg
    - assates/images/master/a3.jpg
    - assates/images/logo/logo3.jpg
    - assates/images/logo/logo4.jpg
    - assates/images/logo/LOGO-KAYAN.png
    - assates/images/logo/zenate.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Al-Jazeera-Arabic
      fonts:
        - asset: assates/fonts/Al-Jazeera-Arabic-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
